### PR TITLE
Add LDAP support for python 3.x

### PR DESCRIPTION
**Pull request by rthill**
This is my implementation running in production using the ldap3 module from https://github.com/cannatag/ldap3/ for Python 3.x.

### CODE REVIEW

**Comment by liZe** [comment]
@rthill Thanks for your PR.

As it's defined in #372, the authentication modules have been removed from Radicale and will be available thanks to external "plugins". Would you be interested in developing the plugin and/or maintaining it?

**Comment by rthill** [comment]
I will develop an LDAP authentication plugin as soon as the documentation
for plugins is ready.

Raoul

**Comment by ge-fa** [comment]
Did this happen in the meantime?

**Comment by liZe** [comment]
There's no documentation, but here is [an example of storage plugin](https://github.com/Kozea/RadicaleStorageByIndex).

If anyone is interested in writting some documentation about plugins, I'm ready to help!

**Comment by xy2** [comment]
Is there some "contrib" section? I slightly rewritten ldap auth by @rthill , so it's "plugin" now:
https://gist.github.com/xy2/eea6d8e72e85fb2fea345264dbd79eb7#file-radicale_auth_ldap-py
Works for my environment.

**Pull request closed without merging**
