### PR TITLE
Catch OSError instead of IOError

### PR DESCRIPTION
**Pull request by untitaker**
If the collection doesn't exist yet, OSError(2, 'No such file or
directory') is raised.

https://travis-ci.org/untitaker/vdirsyncer/jobs/42540595

### CODE REVIEW

**Comment by untitaker** [comment]
@liZe Why can't this be merged before 1.0?

**Comment by liZe** [comment]
Here's what I get for `import codecs;codecs.open('test').read()` (from `filesystem.py`) with no `test` file:
- Python 2.7: `IOError`
- Python 3.4: `FileNotFoundError` (inherits from `OSError`)

We can probably get different errors with `filesystem` and `multifilesystem`, so what do you think of catching both?

**Comment by untitaker** [comment]
Hmm, I think the `IOError` should be catched inside the loop.

**Comment by untitaker** [comment]
Hang on, I'll update my PR.

**Comment by untitaker** [comment]
@liZe I think this is good as-is.

Also I get test failures (from my own testsuite), I'll look into it.

**Pull request merged**
