### PR TITLE
Pbiering testing

### PR DESCRIPTION
**Pull request by pbiering**
splitted now:
- https://github.com/Kozea/Radicale/pull/568

More coming afterwards

=== below historic information ===

Superseeds/includes my older pull requests
- https://github.com/Kozea/Radicale/pull/519
- https://github.com/Kozea/Radicale/pull/518
- https://github.com/Kozea/Radicale/pull/517

and includes also other (merged) pull requests:
- https://github.com/Kozea/Radicale/pull/512
- https://github.com/Kozea/Radicale/pull/521
- https://github.com/Kozea/Radicale/pull/540

and includes:
- Items/Props caching (speed up a lot, one sync request with WP results already in approx. 80% hit), cache statistics are logged after every request or after minimum interval on info level
- request/response logging only if 'debug' option is explicitly given
- add example config for dedicated debug log
- additional debug_filter option to disable some debug logs conditionally
- catch broken items during PUT before storage to filesystem to avoid empty files

it's strongly recommend to use this in combination with
- python-vobjects 0.9.3 + encoding bugfix https://github.com/eventable/vobject/pull/49

Until implemented do not offer "sync-collection" (and "sync-token"), see also
- https://github.com/Kozea/Radicale/issues/306

### CODE REVIEW

**Comment by pbiering** [comment]
It turned out that one request results in multiple file reads and vobject parsing resulting in really slow speed serving requests on a "not-high-end" system - after implementing a simple Item cache this speed up a lot! Will update my testing branch next days with the (optional) caching.

**Comment by pbiering** [comment]
Item cache implemented, for sure not best Python coding, but working well ;-)

**Comment by pbiering** [comment]
Currently known issues:
- strange still undetected memory leak once caching is active resulting in Out-Of-Memory kill by Linux kernel: after a while of having constant RSS (all clients connected, all in cache), RSS suddenly explode in approx. 5 min timerange after some regular requests.

**Comment by pbiering** [comment]
I would consider my pull request now as stable, ran around 10 days with no exception (then a scripted restart was triggered because of a generic phyton34 update:

For all which are interest in the caching feature, here the statistics:
```
2016-11-07 07:45:00,263 - [7fa1873f6740] INFO: Items cache overall statistics: lookup=4247485 hit=4244440 (99.93%) miss=3023 (0.07%) dirty=22 (0.00%) entries=3018 memoryKiB=2951.379
2016-11-07 07:45:00,263 - [7fa1873f6740] INFO: Props cache overall statistics: lookup=754687 hit=754601 (99.99%) miss=29 (0.00%) dirty=57 (0.01%) entries=29 memoryKiB=3.205
```

Environment:
- CentOS 7
- phyton34 + dependencies installed from EPEL
- python34-vobject-0.9.3-10 + mentioned patch (self-made rebuild)

**Comment by liZe** [comment]
Thanks a lot for these changes.

I'm trying to merge your previous PR one by one to get easier diffs to read (I should have done this before).

**Comment by liZe** [comment]
I've merged your previous pull requests and changed minor things, thanks a lot for your work.

I'd like to merge some of your changes before releasing 2.0.0, including your work on logs and catching the bad PUT requests. Caching may be a little bit dangerous, I'd really like to have it in a separate PR to have different reviewers and a talk about this.

Are you interested in splitting this PR, or do you want me to do this for you?

**Comment by pbiering** [comment]
Caching can be disabled by property and e.g. disabled by default. My "pbiering-testing" is now running since some months with caching enabled without any problems, so splitting the PR would be only more work. If you really want to leave it out for the moment, please migrate only the non-caching parts by diff and selective patch, caching code should be identifyable.

**Comment by liZe** [comment]
> splitting the PR would be only more work

You're right. As I'm a bit afraid of memory cache (even if it can be disabled), I'll merge that in the next version.

**Comment by pbiering** [comment]
rebased with current master, try to split in several smaller pull requests now

**Comment by Unrud** [comment]
I'm closing this:

* A separate tool for checking the storage is unnecessary, because error message now contain the paths of invalid files.
* The memory cache is superseded by the on-disk cache.
* The logging filter is too complicated. The non-debugging log output is now less verbose and should contain everything that is required for identifying the cause of problems.
* The various small improvements to log messages got handled by a general overhaul of all log message.
* The examples for log file rotation are included in the documentation.

**Pull request closed without merging**
