### PR TITLE
Added support for webcal-subscriptions

### PR DESCRIPTION
**Pull request by leso-kn**
This PR adds support for webcal subscriptions, as discussed in #776.

Please note, that this is a backend-focused implementation, so efforts to adapt the web UI have not been made in this changeset.

Webcal subscriptions can be added in the form of a collection, just like calendars, todo lists and the like. The URL to the targeted online ICS file, as well as the display name and an optional color for the calendar are stored in the `.Radicale.props` file of the regarding collection.

Steps to subscribe to a calendar manually:

1. Create a new collection (folder) in Radicale's `collection-root/` directory
2. Create a `.Radicale.props` file, structured as shown in the example below

The subscribed calendar will now be advertised by Radicale and should appear in supported applications (e.g. [DAVx⁵](https://f-droid.org/de/packages/at.bitfire.davdroid/) for Android)

Example:

```jsonc
// cat collection-root/[...]/[a collection]/.Radicale.props
{
    "tag": "VSUBSCRIBED",
    "D:displayname": "Online Calendar",
    "ICAL:calendar-color": "#00BBEEFF",
    "CS:source": "https://example.org/online-calendar.ics"
}
```

Result (DAVx⁵ + ICSx⁵):

Screenshot_20220328-191826232 Screenshot_20220328-191846410

### CODE REVIEW

**Comment by anishmittal2020** [comment]
@Unrud Please approve this pull request.

**Comment by dstrelnikov** [comment]
Since Radicale does not announce calendars which do not belong to the user but are accessible to read, this would be a very convenient workaround in my workflow!

**Comment by trougnouf** [comment]
I would like to share my existing Radicale calendars with a public (passwordless) read-only URL so that it works with google calendar and such.
Would this provide that solution or I should create a separate issue from #776  ?

**Comment by OdinVex** [comment]
Would quite like to see this #1229 pulled in, does anyone know someone with write-access?

**Review by pbiering — COMMENTED** [review]
looks like at least not breaking anything

**Comment by OdinVex** [comment]
> looks like at least not breaking anything

Tested with Apache, works fine. Repo org community site is 500, nothing else done to this repo since earlier mid-year.

**Comment by OdinVex** [comment]
> https://radicale.org/ is working, @Unrud : can you approve the pull request?

I meant their GitHub community site, https://community.kozea.fr/.

**Comment by leso-kn** [comment]
**Update:** Upstreamed to master to include latest changes, no merge conflicts.

:information_source: As a side note: the Github Actions configuration seems to be broken though, it's using some outdated python version strings (see [pipeline log](https://github.com/leso-kn/Radicale/actions/runs/4192610326/jobs/7268408805) and the [list](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) of supported python versions of the Github Actions module).

**Comment by MrPixelized** [comment]
Why hasn't this PR been merged yet? Is there anything I can do to help it along?

**Comment by govynnus** [comment]
> Why hasn't this PR been merged yet? Is there anything I can do to help it along?

Same question here :)

**Comment by leso-kn** [comment]
**Update:** Upstreamed to master to include latest changes:

* Adapted code to use the new `collection.tag`-field.

Regarding my previous side note: I see the Github Actions configuration has been fixed, nice! :)
The pipeline is passing on my side.

Using that as a quick reminder that this PR is ready to be merged!

**Comment by leso-kn** [comment]
@Unrud Do you require any additional adjustments to this PR from my side?

**Review by pbiering — APPROVED** [review]
looks good, only extensions

**Comment by mmBesar** [comment]
If it's approved, Why it's not merged yet?!

**Comment by leso-kn** [comment]
@mmBesar There hasn't been much activity on this project lately. The last commit is from mid-April, so I believe the maintainer simply didn't have the time to look into it since this PR was approved.

In case you want to try out an alternative, you may want to check out https://sabre.io/baikal/.

**Comment by mmBesar** [comment]
@leso-kn I have Baikal installed.
Is it possible to subscribe to an online WEBCAL calendar?

**Comment by leso-kn** [comment]
@mmBesar According to https://sabre.io/dav/clients/ical/#subscriptions it should be possible, though it seems like you need to manually create the object (just like with this implementation for Radicale) or use a client that supports adding server-side webcal subscriptions (e.g. iCal).

**Comment by MatthewHana** [comment]
Had a look at the web UI and it wouldn't be difficult to add Webcal support to the UI that builds off @leso-kn's great work. 

+1 for merging this PR.

**Comment by 6801318d8d** [comment]
@Kozea can we merge please?

**Review by pbiering — APPROVED** [review]
ok

**Comment by pbiering** [comment]
@leso-kn : can you please create an empty commit to trigger "actions"? See here for more information: https://stackoverflow.com/questions/52408592/how-to-relaunch-github-check-without-pushing-new-commits

**Comment by leso-kn** [comment]
@pbiering done. Also rebased against master, which makes the docs job fail but that's only due to the branch name. All tests pass on all platforms.

**Comment by pbiering** [comment]
@leso-kn : I have requested enabling GitHub's Wiki for radicale, once enabled it would be great to have example documented there.

**Comment by gentooboontoo** [comment]
@pbiering @leso-kn Radicale's wiki has been enabled again.

**Comment by MatthewHana** [comment]
I have added support for this in the web UI in PR #1329. Thanks again @leso-kn.

**Comment by leso-kn** [comment]
@MatthewHana oh, Nice work! That's very cool

**Pull request merged**
