### PR TITLE
Add manual import of existing calendar to documentation

### PR DESCRIPTION
**Pull request by GuiOm**
Hello,
I had to import an existing calendar, but I didn't find an how to in the documentation.
Based on your reply here : https://github.com/Kozea/Radicale/issues/750 I added the curl command in clients.md to import an ics file.

### CODE REVIEW

**Comment by Unrud** [comment]
The next major release will include an upload dialog in the web interface.

**Comment by Biepa** [comment]
@Unrud How is the status, of the next major release.
Any possible dates?
Waiting for this feature :grimacing:

**Comment by Tntdruid** [comment]
No updated for 7 months now

**Comment by novoid** [comment]
Is my assumption right that this method does not _overwite_ the existing calendar content but it instead adding items to it?
If this holds true, then this is not a method where I periodically need to read-only sync radicale with a complete set of items of an external calendar, right?

Therefore my issue is (in other words): I do have a non-radicale calendar system like Org mode. I periodically export the whole calendar (not just updates) to an ics file. By using the method above, I assume that modified items do not get updated but duplicated instead. Correct?

**Comment by Unrud** [comment]
> By using the method above, I assume that modified items do not get updated but duplicated instead. Correct?

The whole calendar gets overwritten.

**Pull request closed without merging**
