### PR TITLE
Rebase galaxy4public patch on top of bf4f5834

### PR DESCRIPTION
**Pull request by sysnux**
Updated the dovecot pull request https://github.com/Kozea/Radicale/pull/946 from galaxy4public to be compatible with current Radicale3.

### CODE REVIEW

**Comment by pbiering** [comment]
@sysnux thank you very much for the rebased PR, but looks like test suite on Windows is not running:

```
ERROR    radicale:__init__.py:117 An exception occurred during PROPFIND request on '/': module 'socket' has no attribute 'AF_UNIX'
Traceback (most recent call last):
```

Best would be to exclude the auth/dovecot tests on Windows platform where it would be very unexpected that one runs here _dovecot_ in parallel.

**Comment by sysnux** [comment]
You are right, unfortunately I don't know how to that.

**Comment by pbiering** [comment]
> You are right, unfortunately I don't know how to that.

Can you try short after `def _test_dovecot(..` detect OS and skip (but log) the test.

Found a code sniplet which should be able to support test exclusion based on OS:

```
>>> import os

>>> os.name
'nt'

>>> import platform

>>> platform.system()
'Windows'
```

See also https://stackoverflow.com/questions/1854/how-to-identify-which-os-python-is-running-on

As I have no Python on Windows running, potentially some try and errors are required until working well.

**Comment by sysnux** [comment]
Documentation added.
New try at skipping tests on Windows...

**Pull request merged**
