### PR TITLE
some Dockerfile improvements

### PR DESCRIPTION
**Pull request by funkyfuture**
i know that Docker support is canny here, but i found that opportunity to reduce the images' size and couldn't resist to wipe some opinionated comments that don't fit all deployment environments.

### CODE REVIEW

**Comment by felixfontein** [comment]
> wipe some opinionated comments that don't fit all deployment environments.

I'd rather understand them as instructions for beginners. People who know how Docker works will ignore them anyway.

**Comment by funkyfuture** [comment]
> I'd rather understand them as instructions for beginners.

i do not think that these comments would help beginners at all. they might even endorse bad practices. proper instructions would be prose in the docs.

> People who know how Docker works will ignore them anyway.

i did not.

**Comment by nullinger** [comment]
I did quite the same as @funkyfuture in my Dockerfile and follow his argumentation.

**Comment by Unrud** [comment]
Thank you.

**Pull request merged**
