### PR TITLE
obtaining creds from env can now be overridden in plugins

### PR DESCRIPTION
**Pull request by jaesivsm**
Following the discussion in #499 I extracted the credentials obtaining from the main module to the auth module so that it can be overridden in a plugin.

### CODE REVIEW

**Comment by Unrud** [comment]
I'm not sure if this is really useful. Either Radicale handles authentication by itself or leaves it to the web server (REMOTE_USER env. var.), there are no other options that could be implemented in plugins.

**Comment by jaesivsm** [comment]
Well it allows to clearly define where you take your user from. I don't think they are use cases where both `HTTP_AUTHENTICATION` and `REMOTE_USER` are used at the same. Such case would not be actually supported indeed.

As this feature was removed when storages, auths and other stuffs like that were cleaned I assumed Radicale was wanted to work in a single way. That's why plugins were made available.

> there are no other options that could be implemented in plugins.

I can imagine other auth mechanism overriding that part also. Leaving the possibility open doesn't seem harmful to me. 

But again, I do not stand by that solution firmly.

**Comment by Unrud** [comment]
> I don't think they are use cases where both HTTP_AUTHENTICATION and REMOTE_USER are used at the same.

True. I think that a configuration option to switch between both would be enough.

> I can imagine other auth mechanism overriding that part also.

Do you have an example?

**Comment by jaesivsm** [comment]
> Do you have an example?

Well not really. But for one the http auth mechanism doesn't have to be `Basic` (see https://tools.ietf.org/html/rfc2617#section-3) and I can imagine user implementing kerberos token over that.

**Comment by Unrud** [comment]
> But for one the http auth mechanism doesn't have to be ``Basic`` (see https://tools.ietf.org/html/rfc2617#section-3)

If you want implement anything besides ``Basic``, you also have to expose the response headers to the module.

> I can imagine user implementing kerberos token over that.

Sure, you can also just use a web server that handles this.

**Comment by jaesivsm** [comment]
> If you want implement anything besides Basic, you also have to expose the response headers to the module.

https://github.com/Kozea/Radicale/pull/504/commits/568f804da7781492e60279c49d925b7a14a8f50a#diff-058c90db22e1ad548ea5699e233221b3R92

> Sure, you can also just use a web server that handles this.

As for Basic auth, or parsing htpasswd files or many other stuffs that are implemented in Radicale. I don't see your point.

**Comment by Unrud** [comment]
> As for Basic auth, or parsing htpasswd files or many other stuffs that are implemented in Radicale. I don't see your point.

If you want to use something complicated like Kerberos it's much easier to use a web server that already supports it. The same is true for other less-used authentication methods like client-side certificates.

I think that Basic and Digest are the only widely supported methods. Digest could be implemented in addition to Basic (without a plug-in module), on the other hand you can also just enable SSL which is much more secure.

**Comment by jaesivsm** [comment]
This way we would have Basic, Digest, and the remote user half implemented in the default auth module (since the other part is the user retrieving from the context and it would take place in the main code). That looks a bit v1-ish to me.

I thought the whole point of splitting into main project and plugins was to avoid this. It's a design choice.

**Comment by Unrud** [comment]
My concern is that this PR adds complexity without any real gain. In it's current state it's not even possible to extent Radicale with a plug-in  module beyond Basic auth and REMOTE_USER. Client side certificates are even impossible with this approach, you would need to extent the integrated server.

I have the feeling that nobody will ever use it, and instead just setup **nginx** or similar.

**Comment by jaesivsm** [comment]
> My concern is that this PR adds complexity without any real gain.

I'm moving code around, removing auth retrieving from the main module and pasting it into the auth module. I didn't really write any new code so no complexity is added; the code is just more organized. 

If you don't think that part of the code belong there and you want more control structure in the main module to deal with `REMOTE_USER`s and configuration then I don't think we can come to an agreement.

But again that's a very minor change anyway.

**Comment by Unrud** [comment]
Implemented in #612

**Pull request closed without merging**
