### PR TITLE
Allow creation of empty collection via PUT

### PR DESCRIPTION
**Pull request by Unrud**
If an empty collections is created with PUT, content is None.

### CODE REVIEW

**Comment by untitaker** [comment]
For creating collections you ought to use MKCOL/MKCALENDAR, not PUT. Am I missing something?

Also there probably should be some sort of assertion that only one item is uploaded, instead of silently discarding leftovers.

**Comment by Unrud** [comment]
> For creating collections you ought to use MKCOL/MKCALENDAR, not PUT. Am I missing something?

I don't think that this is in the specification, but some clients use it.

**Comment by untitaker** [comment]
Which clients in particular? I don't know of a server that supports this either, so I am not sure if it is possible.

**Comment by Unrud** [comment]
> Which clients in particular?

Outlook

**Comment by untitaker** [comment]
Ok, however your PR still doesn't seem to have this effect. PUT on collections returns 201 without doing anything.

**Comment by liZe** [comment]
Thank you!

**Pull request merged**
