### PR TITLE
Processing expand property

### PR DESCRIPTION
**Pull request by metallerok**
https://github.com/Kozea/Radicale/issues/662

### CODE REVIEW

**Comment by pbiering** [comment]
@metallerok : can you please explain more details about this PR

**Comment by metallerok** [comment]
In accordance with https://www.rfc-editor.org/rfc/rfc4791#section-9.6.5 (9.6.5 CALDAV:expand XML Element), a REPORT request can specify the `expand` property, which forces the server to expand recurring components into individual recurrence instances for a specified period. 
Example https://www.rfc-editor.org/rfc/rfc4791#section-7.8.3

**Comment by pbiering** [comment]
@metallerok : would it be able to create also a test case for this kind of support?

**Comment by pbiering** [comment]
@metallerok : thank you for the PR, but looks like the test run is not happy...please check and update your PR.
See also https://github.com/Kozea/Radicale/wiki/Contributions

**Review by pbiering — APPROVED** [review]
ok

**Comment by pbiering** [comment]
Code validation is not working on updated PRs, currently also no clue how to trigger manually...
but extended documentation further on how to run locally: https://github.com/Kozea/Radicale/wiki/Contributions

````
radicale/app/report.py:72: error: Need type annotation for "props"  [var-annotated]
radicale/app/report.py:224: error: Item "None" of "Optional[Any]" has no attribute "serialize"  [union-attr]
radicale/tests/test_base.py:1550: error: Item "int" of "Union[int, dict[str, tuple[int, Element]]]" has no attribute "values"  [union-attr]
radicale/tests/test_base.py:1558: error: Need type annotation for "uids" (hint: "uids: List[<type>] = ...")  [var-annotated]
radicale/tests/test_base.py:1590: error: Item "int" of "Union[int, dict[str, tuple[int, Element]]]" has no attribute "values"  [union-attr]
Found 5 errors in 2 files (checked 73 source files)
```

Had to fix also  a report by `isort`, so please rebase before submitting further fix

**Comment by metallerok** [comment]
@pbiering mypy gives strange results, here is the code from an existing test
```python
        self.put(event_path, event)
        _, responses = self.report(event_path, """\
<?xml version="1.0" encoding="utf-8" ?>
<C:calendar-query xmlns:C="urn:ietf:params:xml:ns:caldav">
    <D:prop xmlns:D="DAV:">
        <D:getetag />
    </D:prop>
</C:calendar-query>""")
        assert len(responses) == 1
        response = responses[event_path]
        assert not isinstance(response, int)
        status, prop = response["D:getetag"]
        assert status == 200 and prop.text
```

and here is the code from my test
```python
        self.put("/calendar.ics/", get_file_content("event_daily_rrule.ics"))
        req_body_without_expand = ...
        _, responses = self.report("/calendar.ics/", req_body_without_expand)
        assert len(responses) == 1

        response_without_expand = responses['/calendar.ics/event_daily_rrule.ics']
        status, element = response_without_expand["C:calendar-data"]

        assert status == 200
```

But mypy doesn’t respond to the first section of the code, and to mine it gives an error, not understanding that the result is being unpacked.

And another question: should I add validation fixes to the current branch or to a new one?

```
> .venv/bin/python -c 'import importlib.util, subprocess, sys; importlib.util.find_spec("mypy") and sys.exit(subprocess.run(["mypy", "."]).returncode) or print("Skipped: mypy is not installed")'
```

```
radicale/tests/test_base.py:1551: error: Value of type "Union[int, Dict[str, Tuple[int, Element]]]" is not indexable  [index]
radicale/tests/test_base.py:1555: error: Unsupported right operand type for in ("Union[Any, str, None]")  [operator]
radicale/tests/test_base.py:1556: error: Unsupported right operand type for in ("Union[Any, str, None]")  [operator]
radicale/tests/test_base.py:1557: error: Unsupported right operand type for in ("Union[Any, str, None]")  [operator]

```

image

**Pull request merged**
