### PR TITLE
Log to syslog, too.

### PR DESCRIPTION
**Pull request by kousu**
Hiya! :tulip: 

I read your docs and I [saw](https://radicale.org/3.0.html#documentation/logging)

> Radicale logs to `stderr`.

I like the [12 factor app](https://12factor.net/) too, but unfortunately BSD has no way built to capture stderr logs: it expects programs to use syslog. I set up this [start script](https://man.openbsd.org/rc.d)

<details><summary>/etc/rc.d/radicale</summary>

```
#!/bin/ksh

daemon="/usr/local/bin/radicale"
daemon_user="_radicale"

. /etc/rc.d/rc.subr

rc_start() {
        ${rcexec} "${daemon} ${daemon_flags} &"
}

pexp="/usr/local/bin/python3.8 /usr/local/bin/radicale"

rc_cmd $1
```

</details>

and with that `rcctl start radicale` works, but it loses the logs, which made debugging my deployment difficult.

I noticed that, though undocumented, you respect WSGI redirecting logs:

https://github.com/Kozea/Radicale/blob/f72b3449818600962268bc96a2a12e8e022a0c42/radicale/log.py#L21-L24

so I thought maybe you'd be open to syslog as well? What do you think?

### CODE REVIEW

**Comment by kousu** [comment]
Or, if you would rather not have this, can you help me adapt https://radicale.org/3.0.html#tutorials/running-as-a-service to use `gunicorn`? I know `gunicorn` [supports syslog](https://docs.gunicorn.org/en/stable/settings.html#syslog) but your docs don't recommend it and it would help, if that is what you expected people who want to use syslog to do, to include a small guide on what and where settings need to change to make that happen.

**Comment by ehem** [comment]
In my mind this would be an acceptable resolution to the key issue in bug reports #1085 and #1188.  Modern practice has tended to disfavor the system log, but it is still a fully functional logging method.  As this issue is a major problem, I think this should be accepted.

**Review by ehem — COMMENTED** [review]
Upon testing, this wasn't working for me.  Oddly my reading of the documentation suggests this _should_ work, yet it seems logging.handler may not exist on this system, disagreeing with the documentation.

The general approach seems right, just wasn't working for me when testing.

**Comment by kousu** [comment]
Thank you for taking a look @ehem. Maybe I messed up somehow. I only tested this on OpenBSD, too -- I wasn't even sure you'd be interested -- so I could've easily missed something.

**Comment by kousu** [comment]
Here's what I see, on OpenBSD 6.9:

If started like

```
comms3# doas -u _radicale radicale --logging-level debug 
[2022-01-21 17:24:31 +0100] [79626] [INFO] Loaded default config
[2022-01-21 17:24:31 +0100] [79626] [INFO] Loaded config file '/etc/radicale/config'
[2022-01-21 17:24:31 +0100] [79626] [INFO] Skipped missing config file '/var/lib/radicale/.config/radicale/config'
[2022-01-21 17:24:31 +0100] [79626] [INFO] Loaded arguments
[2022-01-21 17:24:31 +0100] [79626] [INFO] Starting Radicale
[2022-01-21 17:24:31 +0100] [79626] [INFO] auth type is 'radicale.auth.bsdauth'
[2022-01-21 17:24:31 +0100] [79626] [INFO] storage type is 'radicale.storage.multifilesystem'
[2022-01-21 17:24:31 +0100] [79626] [INFO] rights type is 'radicale.rights.owner_only'
[2022-01-21 17:24:31 +0100] [79626] [INFO] web type is 'radicale.web.internal'
[2022-01-21 17:24:31 +0100] [79626] [INFO] Listening on '[0.0.0.0]:5232' with SSL
[2022-01-21 17:24:31 +0100] [79626] [INFO] Listening on '[::]:5232' with SSL
[2022-01-21 17:24:31 +0100] [79626] [INFO] Radicale server ready
```

then I get

```
comms3# tail -n 0 -f daemon
Jan 21 17:24:31 comms3 Loaded default config
Jan 21 17:24:31 comms3 Loaded config file '/etc/radicale/config'
Jan 21 17:24:31 comms3 Skipped missing config file '/var/lib/radicale/.config/radicale/config'
Jan 21 17:24:31 comms3 Loaded arguments
Jan 21 17:24:31 comms3 Starting Radicale
Jan 21 17:24:31 comms3 auth type is 'radicale.auth.bsdauth'
Jan 21 17:24:31 comms3 storage type is 'radicale.storage.multifilesystem'
Jan 21 17:24:31 comms3 rights type is 'radicale.rights.owner_only'
Jan 21 17:24:31 comms3 web type is 'radicale.web.internal'
Jan 21 17:24:31 comms3 Listening on '[0.0.0.0]:5232' with SSL
Jan 21 17:24:31 comms3 Listening on '[::]:5232' with SSL
Jan 21 17:24:31 comms3 Radicale server ready
```

I get identical output with `doas -u _radicale radicale --logging-level info`.

But without `--logging-level` I get nothing, neither to stderr nor /var/log/daemon:

```
comms3# doas -u _radicale radicale                      

```

```
comms3# tail -n 0 -f daemon 

```

is it possible that your test setup isn't working because you need to specify the log level?


I added to `/etc/radicale/config`:

```
[logging]
level = info
```

and now using my startup script (above):

```
comms3# rcctl start radicale
radicale(ok)
```

produces the same output to syslog again:

<details>

```
comms3# tail -n 0 -f daemon
Jan 21 17:28:10 comms3 Loaded default config
Jan 21 17:28:10 comms3 Loaded config file '/etc/radicale/config'
Jan 21 17:28:10 comms3 Skipped missing config file '/var/lib/radicale/.config/radicale/config'
Jan 21 17:28:10 comms3 Starting Radicale
Jan 21 17:28:10 comms3 auth type is 'radicale.auth.bsdauth'
Jan 21 17:28:10 comms3 storage type is 'radicale.storage.multifilesystem'
Jan 21 17:28:10 comms3 rights type is 'radicale.rights.owner_only'
Jan 21 17:28:10 comms3 web type is 'radicale.web.internal'
Jan 21 17:28:10 comms3 Listening on '[0.0.0.0]:5232' with SSL
Jan 21 17:28:10 comms3 Listening on '[::]:5232' with SSL
Jan 21 17:28:10 comms3 Radicale server ready
```

</details>

**Comment by kousu** [comment]
I just realized I haven't thought through how to integrate the syslog handler with the pre-existing handlers. It seems to be ignoring

https://github.com/Kozea/Radicale/blob/57a308b524433c3a7166ff15fdfe9ee8893d1363/radicale/log.py#L37

Is that because it's not running through

https://github.com/Kozea/Radicale/blob/57a308b524433c3a7166ff15fdfe9ee8893d1363/radicale/log.py#L71-L73

?

**Review by ehem — COMMENTED** [review]
I'm unsure whether my system has the odd Python setup, versus your's.  I'm looking at Python 3.9.

I needed to add `import logging.handlers` to get this to run.  Now to wait and see whether any interesting messages show up...

**Comment by kousu** [comment]
> I'm unsure whether my system has the odd Python setup, versus your's. I'm looking at Python 3.9.

Ah that could've been it. I have 3.8:

<details>

```
comms3# uname -a
OpenBSD comms3.kousu.ca 6.9 GENERIC#5 amd64
comms3# python --version
ksh: python: not found
comms3# python3 --version
Python 3.8.11
comms3# pkg_info python
Information for inst:python-2.7.18p1

Comment:
interpreted object-oriented programming language

Required by:
py-pip-20.3.4
py-setuptools-44.1.1v0

Description:
Python is an interpreted, interactive, object-oriented
programming language that combines remarkable power with
very clear syntax. For an introduction to programming in
Python you are referred to the Python Tutorial. The Python
Library Reference documents built-in and standard types,
constants, functions and modules. Finally, the Python
Reference Manual describes the syntax and semantics of the
core language in (perhaps too) much detail.

Python's basic power can be extended with your own modules
written in C or C++.  On most systems such modules may be
dynamically loaded. Python is also adaptable as an
extension language for existing applications. See the
internal documentation for hints.

Maintainer: Remi Pointel <rpointel@openbsd.org>

WWW: https://www.python.org/


Information for inst:python-3.8.11

Comment:
interpreted object-oriented programming language

Required by:
glib2-2.66.8
py3-aiohttp-3.7.4
py3-async-timeout-3.0.0p1
py3-attrs-20.1.0
py3-chardet-4.0.0
py3-gunicorn-20.0.4p1
py3-idna-2.10
py3-multidict-4.7.5p1
py3-pip-20.3.4
py3-setuptools-44.1.1v0
py3-typing_extensions-3.7.4.1p0
py3-yarl-1.4.2p3
python3-3.8p0

Description:
Python is an interpreted, interactive, object-oriented
programming language that combines remarkable power with
very clear syntax. For an introduction to programming in
Python you are referred to the Python Tutorial. The Python
Library Reference documents built-in and standard types,
constants, functions and modules. Finally, the Python
Reference Manual describes the syntax and semantics of the
core language in (perhaps too) much detail.

Python's basic power can be extended with your own modules
written in C or C++.  On most systems such modules may be
dynamically loaded. Python is also adaptable as an
extension language for existing applications. See the
internal documentation for hints.

Maintainer: Remi Pointel <rpointel@openbsd.org>

WWW: https://www.python.org/

```

</details>

According to https://openports.se/meta/python3, 3.9 has landed on OpenBSD now, and it's been long enough now that if I do a [`sysupgrade`](http://man.openbsd.org/sysupgrade) I should get it. I'm taking it easy this week so maybe I'll budget some of that for a very slow sysadmin/testing day.

**Comment by kousu** [comment]
Alright I've patched this with `import logging.handlers`, which makes it run on all pythons. I didn't realize the problem you were having was that simple, @ehem. It was just an oversight on my part. I don't know why it worked on 3.8 and not 3.9, probably some tweak to the import rules.

But with this patch, now on **linux-with-systemd**, the logs are duplicating, which isn't great:

```
$ sudo journalctl -f
Apr 20 16:47:20 linux-test.kousu.ca radicale[17543]: Skipped missing config file '/.config/radicale/config'
Apr 20 16:47:20 linux-test.kousu.ca radicale[17543]: [2022-04-20 16:47:20 -0400] [17543] [INFO] Skipped missing config file '/.config/radicale/config'
Apr 20 16:47:20 linux-test.kousu.ca radicale[17543]: Starting Radicale
Apr 20 16:47:20 linux-test.kousu.ca radicale[17543]: [2022-04-20 16:47:20 -0400] [17543] [INFO] Starting Radicale
Apr 20 16:47:20 linux-test.kousu.ca radicale[17543]: auth type is 'radicale.auth.none'
Apr 20 16:47:20 linux-test.kousu.ca radicale[17543]: [2022-04-20 16:47:20 -0400] [17543] [INFO] auth type is 'radicale.auth.none'
```

On OpenBSD it works great, and presumably the same for non-systemd Linux (like wheezy, like devaun). But to handle all platforms I think we'd have to re-add a `--log syslog` / `--log stderr` option. [v2 used to have](https://radicale.org/v2.html#logging-1), the ability to log to a file, or a series of files, but already was warning

> [stderr] is the recommended configuration for use with modern init systems (like systemd) or if you just test Radicale in a terminal.
> 
> You can configure Radicale to write its logging output to files (and even rotate them). This is useful if the process daemonizes or if your chosen method of running Radicale doesn't handle logging output.

And the feature was removed in https://github.com/Kozea/Radicale/commit/54b9995e22c7d30d3cd5c99ecd98a5f3ba103b2b, apparently as part of a general clean up of code that had gotten out of hand. It looks like directly writing to syslog was never a feature, though.

**Comment by kousu** [comment]
I spent a while digging around more on OpenBSD's [`rcctl(8)`](https://man.openbsd.org/rcctl.8) and, though it wasn't totally obvious (since it seems to be opt-in instead of opt-out like `systemd`/`journalctl`), OpenBSD **is also on team log-to-stderr**: you need to enable [`daemon_logger`](http://man.openbsd.org/rc.d).

So, with **this**

<details><summary><code>/etc/rc.d/radicale</code></summary>

```
#!/bin/ksh

daemon="/usr/local/bin/radicale"
daemon_user="_radicale"
daemon_logger="daemon.info"

. /etc/rc.d/rc.subr

rc_start() {
        ${rcexec} "${daemon_logger:+set -o pipefail; }${daemon} ${daemon_flags}${daemon_logger:+ 2>&1 |
                logger -ip ${daemon_logger} -t ${_name}} &"
}

pexp="/usr/local/bin/python3.8 /usr/local/bin/radicale"

rc_cmd $1
```

</details>

Then logging works:

```
comms3$ doas rcctl restart radicale 
radicale(ok)
radicale(ok)
comms3$ tail -f /var/log/daemon                                                                                                                      
Apr 20 23:59:12 comms3 radicale[50414]: [2022-04-20 23:59:12 +0200] [79404] [INFO] Loaded config file '/etc/radicale/config'
Apr 20 23:59:12 comms3 radicale[50414]: [2022-04-20 23:59:12 +0200] [79404] [INFO] Skipped missing config file '/var/lib/radicale/.config/radicale/config'
Apr 20 23:59:12 comms3 radicale[50414]: [2022-04-20 23:59:12 +0200] [79404] [INFO] Starting Radicale
Apr 20 23:59:12 comms3 radicale[50414]: [2022-04-20 23:59:12 +0200] [79404] [INFO] auth type is 'radicale_bsdauth'
Apr 20 23:59:12 comms3 radicale[50414]: [2022-04-20 23:59:12 +0200] [79404] [INFO] storage type is 'radicale.storage.multifilesystem'
Apr 20 23:59:12 comms3 radicale[50414]: [2022-04-20 23:59:12 +0200] [79404] [INFO] rights type is 'radicale.rights.owner_only'
```


This was only added [11 months](https://www.openbsd.org/69.html) [ago](https://www.openbsd.org/plus69.html)

> Added [logger(1)](https://man.openbsd.org/logger.1) support to [rcctl(8)](https://man.openbsd.org/rcctl.8), [rc.subr(8)](https://man.openbsd.org/rc.subr.8) and [rc.d(8)](https://man.openbsd.org/rc.d.8) for daemons logging to stdout/stderr.

which is maybe why I missed it.

Given that OpenBSD is on board with the "modern init systems (like systemd)" vibe, and I usually respect their opinions, I'm going to withdraw this.

I still think there could be room in radicale for a syslog option -- the file logging option was wayyyy too complicated, but syslog is a lot tamer -- but the number of platforms where it's a pressing issue is shrinking, and having less places to configure logging is an improvement.  So sorry @ehem, I know you want to keep the old standards working but I think this isn't a hill I'm going to die on. I just wanted to get my logs out somewhere.

**Comment by ehem** [comment]
> Given that OpenBSD is on board with the "modern init systems (like systemd)" vibe, and I usually respect their opinions, I'm going to withdraw this.

Unless there is a message "We fully endorse this", that hardly seems like they're onboard.  This seems more they're willing to provide a hack since far too many recently written programs are broken in this fashion.
This is an example of the classic strategy from a particular Redmond company.  Logging messages sent to standard output is incompatible with existing standards, so get everyone to embrace and you've broken all alternatives.  Unfortunately if the feature is handy enough the tactic is rather effective.

I hadn't been thinking about `logger` though.  Could be reasonably possible to emulate what OpenBSD has likely done internally.  The `radicale` program could pipe its standard output and error to a `logger` process.  Shouldn't be too difficult actually, though I'm thinking at the system call layer which Python may not provide easy access to.

**Comment by kousu** [comment]
> Unless there is a message "We fully endorse this", that hardly seems like they're onboard. This seems more they're willing to provide a hack since far too many recently written programs are broken in this fashion. This is an example of the classic strategy from a particular Redmond company. Logging messages sent to standard output is incompatible with existing standards, so get everyone to embrace and you've broken all alternatives. Unfortunately if the feature is handy enough the tactic is rather effective.

Thanks for the support! It is really annoying when working standards get broken. But in this case I'm coming around to the idea that `stdout` as a standard predates `syslog`, and [it's good to go back to that](https://12factor.net/logs). I'd rather manage logging in a standard way across all my daemons with `rcctl` (on OpenBSD) or `systemd` or even `kubectl` if I have to use that, than dig around inside config files and manpages to get everything just right for all the components I'm using.

> I hadn't been thinking about `logger` though. Could be reasonably possible to emulate what OpenBSD has likely done internally. The `radicale` program could pipe its standard output and error to a `logger` process. Shouldn't be too difficult actually, though I'm thinking at the system call layer which Python may not provide easy access to.

That's what I wrote the initscript above to do -- based on many other initscripts on OpenBSD doing the same thing:

```
        ${rcexec} "${daemon_logger:+set -o pipefail; }${daemon} ${daemon_flags}${daemon_logger:+ 2>&1 |
                logger -ip ${daemon_logger} -t ${_name}} &"
```

`2>&1 | logger` is exactly the key part. There's no need to edit `radicale` itself to do this.

And `logger` is posix. It's [available on Ubuntu](https://manpages.ubuntu.com/manpages/jammy/en/man1/logger.1.html) in [`bsdutils`](https://packages.ubuntu.com/jammy/bsdutils), so I assume it's available everywhere if you want to use it.

But on Ubuntu you already have a .service file which makes it log into systemd instead.

**Pull request closed without merging**
