### PR TITLE
Update of the interface design

### PR DESCRIPTION
**Pull request by Co-7**
Hello, this pull request is just to slightly update the design of the Radicale web interface.

### CODE REVIEW

**Comment by Jeinzi** [comment]
Works and looks good :+1: 

### Before & After
#### Login Page
login-before
login-after

#### Overview Page
overview-before
overview-after


#### Edit Page
screenshot_2023-07-31T00:08:29
screenshot_2023-07-31T00:10:11

**Review by pbiering — APPROVED** [review]
ok

**Comment by pbiering** [comment]
this is in conflict with https://github.com/Kozea/Radicale/pull/1329

@Co-7  / @MatthewHana : please sort out which one is the better

**Comment by MatthewHana** [comment]
Hello @Co-7, I had incorporated a lot of your design changes (1 year after you) into PR #1329. Is there anything you feel I did not incorporate into my UI and should?

The last major changes to the web UI was in 2020 and I do believe that a new and fresh web UI is needed for Radicale. Respectfully, can you please have a look at PR #1329 and consider.

**Comment by Co-7** [comment]
The @MatthewHana interface seems to me to be more accomplished than the very simple interface I made a while ago. You can use @MatthewHana without any worries 😉

**Comment by MatthewHana** [comment]
> The @MatthewHana interface seems to me to be more accomplished than the very simple interface I made a while ago. You can use @MatthewHana without any worries 😉

Thank you, @Co-7. 🙏

**Comment by pbiering** [comment]
Superseeded

**Pull request closed without merging**
