### PR TITLE
Test and fix auth module. Configurable delay. Improve logging.

### PR DESCRIPTION
**Pull request by Unrud**
* Repair the tests for the auth module (they were not working at all).
  * Add tests for all hash methods and also test with wrong usernames and passwords.
  * Fix the SSHA method.
  * Compare in constant time.
  * Add configuration option for the delay.
  * Don't apply the delay for clients that didn't try to authenticate.

This PR is also merged into https://github.com/Unrud/Radicale.

### CODE REVIEW

**Comment by liZe** [comment]
Thanks **a lot** for this. :heart:

The situation is way better with these commits, even if I'm not sure that it fixes the security problem correctly. We probably need at least to:
- use `compare_digest` for logins, and
- test the password even if the logins don't match.

@Unrud @jvoisin What do you think of that?

**Comment by jvoisin** [comment]
I wholeheartedly agree :)

**Comment by Unrud** [comment]
> I'm not sure that it fixes the security problem correctly

I ignored the user names, because the timing attacks seems pretty unrealistic to me. To pull this off you would have to learn the internal state of Python's PRNG from delays with network jitter. Next you would have to compare the response times of different user names (again with network jitter). To do all of this you have less than 20 tries per second (because of the delay and maximal number of parallel connections.)

You do all of this, just to learn if a user name exists or not.

**Comment by liZe** [comment]
> I ignored the user names, because the timing attacks seems pretty unrealistic to me.

Indeed. My deep feeling about that is that it's bullsh^H useless. But some some smart people sent me private mails with long security papers that convinced me to try to fix this issue correctly.

**Comment by jvoisin** [comment]
@Unrud no need to play with the PRNG, just launch your attack over a long period of time: if you're not monitoring your instance, odds are that you won't see my 20 requests per second during 6 months ;)
There was a [paper]( https://www.blackhat.com/docs/us-15/materials/us-15-Morgan-Web-Timing-Attacks-Made-Practical-wp.pdf ) two years ago at Blackhat US about this, and attacks are only getting better.

An interesting threat model would be hidden-services, where people are dumb enough to use their everyday-nick to login on it.

But yeah, I agree, it's completely overkill. But it's cheap, doesn't bloat the code, so why not.

**Pull request merged**
