### PR TITLE
pyupgrade --py38-plus

### PR DESCRIPTION
**Pull request by deronnax**
Mostly remove dead python < 3.8 code.

Btw, what is the python support policy ? When is python 3.8 support dropping ?

### CODE REVIEW

**Comment by deronnax** [comment]
wtf pypy segfault

**Comment by pbiering** [comment]
> Btw, what is the python support policy ? When is python 3.8 support dropping ?

Python 3.8 has EOSL 2024-10 - I assume the for github workflows used template will disappear afterwards.

For Enterprise Linux 8 since 3.2.0 Python 3.9 is selected during packaging, so support for 3.8 is not mandatory anymore.

See also:
https://github.com/Kozea/Radicale/wiki#tested-python-versions

**Comment by pbiering** [comment]
> Mostly remove dead python < 3.8 code.

I would not remove "dead" code so far unless complains are received that existing version is not running with < 3.8 at all. Current status is that it cannot be tested anymore using github workflow.

BTW: there is also a poll available: https://github.com/Kozea/Radicale/discussions/1408

**Comment by pbiering** [comment]
some tests failing, can you please check?

**Comment by deronnax** [comment]
I'll take care, yes. Regarding python 3.8: if it can't be tested anymore, it is now probably broken, so don't bother and remove the dead code.

**Comment by pbiering** [comment]
> Regarding python 3.8: if it can't be tested anymore, it is now probably broken, so don't bother and remove the dead code.

For now Python 3.8 should be still testable hopefully

**Comment by deronnax** [comment]
I meant: python < 3.8, sorry. Currently, due to [this line in the setup.py](https://github.com/Kozea/Radicale/blob/master/setup.py#L63), Radicale will refuse to install on python 3.7 and older. Python 3.7 has been released 6 years ago and is end of life for 1,5 years now. Even without removing dead code, after this MR is merged, it's pretty sure Radicale won't run anymore on 3.7. If you are not OK with this, just close this MR.

**Comment by pbiering** [comment]
> I meant: python < 3.8, sorry. Currently, due to [this line in the setup.py](https://github.com/Kozea/Radicale/blob/master/setup.py#L63), Radicale will refuse to install on python 3.7 and older. Python 3.7 has been released 6 years ago and is end of life for 1,5 years now. Even without removing dead code, after this MR is merged, it's pretty sure Radicale won't run anymore on 3.7. If you are not OK with this, just close this MR.

Support of Python 3.7 ended with 3.1.9, see also https://github.com/Kozea/Radicale/wiki

Also test suite is not testing 3.7 anymore, but 3.u triggers still an issue

https://github.com/Kozea/Radicale/actions/runs/10265934628/job/28403176547?pr=1553

It's a segfault, somehow strange, potentially a glitch, can you commit a more or less empty change to be able to retrigger the tests?

**Comment by deronnax** [comment]
we have the answer: it was a glitch. It can be merged.

**Pull request merged**
