### PR TITLE
Add vdirsyncer tests, tox.ini refactor

### PR DESCRIPTION
**Pull request by untitaker**
See #29

### CODE REVIEW

**Comment by untitaker** [comment]
**This is a WIP, please don't merge yet**

**Comment by untitaker** [comment]
@liZe Like https://github.com/pimutils/vdirsyncer/pull/428, this shows the same issues in the vobject library.

**Comment by liZe** [comment]
:cry:

**Comment by Unrud** [comment]
Closing because of age.

**Pull request closed without merging**
