### PR TITLE
htpasswd-based authentication: implement MD5-APR1 and BCRYPT support via passlib

### PR DESCRIPTION
**Pull request by jgehrcke**
This addresses https://github.com/Kozea/Radicale/issues/293.

### CODE REVIEW

**Comment by jgehrcke** [comment]
Not really sure what happened: this should be just two commits, not three (the empty merge is weird). Locally I had rebased onto master and squashed cleanly. Will look into this tomorrow, or is this already fine enough?

**Comment by jgehrcke** [comment]
I have properly rebased my branch, so this could now be merged w/o polluting history. No we can discuss this (feedback really appreciated).

I think this should necessarily wait for Radicale 2.0. I believe it should be merged into the latest release line, because it enables **secure** password storage via htpasswd for the first time. This would also close the one-year-old discussion in #118. There, usage of passlib was also suggested. I have seen in multiple instances on the web that people mess with Radicale's htpasswd code in production for "fixing" the lack of proper password encryption themselves. This would not be necessary anymore. This is a feature that users desperately need, maybe without knowing.

### Overview 
The implementation proposed in this pull request implements a "progressive enhancement", i.e. provides additional crypto features upon availability of passlib and upon availability of a bcrypt backend for passlib. It provides meaningful error messages in case a certain crypto method is requested via config file, but is not supported by the run time.

### Error messages
The error messages provided by the proposed implementation (about mismatch between config and runtime availability) actually are exception values within RuntimeError exceptions. I have looked at the current architecture of Radicale and figured that this probably fits the existing code best (an alternative would have been to error out via `sys.exit("error message")`, for example). Feedback appreciated. It leaves to be mentioned that named mismatch is detected upon Radicale *start up*, instead of only catching this upon the first request.

### Tests
Clearly my goal was to not touch or invalidate existing unit tests. Didn't do so. However, the test coverage is not too great so far. I think proper testing of all htpasswd features proposed in this implementation requires some better unit test infrastructure, but I did not want to go ahead and propose drastic changes in this regard.

So, most importantly, the current unit tests pass with the proposed changes and I have on top of that tested various scenarios manually. That is, I am quite certain that the proposed changes could be releasex as 0.X w/o breaking anyone's system when upgrading.

### Config file annotation
Once we decide to merge this, the config file commentary should also be updated to reflect the new features, but also their security implications. The config file should express in simple terms that certain methods are plain insecure to use. I can do so if desired.

Thanks for all your work on Radicale and I hope we can include these features!

**Comment by liZe** [comment]
Really good job! I'm OK with the implementation choices, the code is clean and simple. Adding some tests and trying the code in real life are the next steps, and it will happen soon as it's no merged in master.

**Comment by jgehrcke** [comment]
Thanks for the quick feedback!

**Pull request merged**
