### PR TITLE
Add ldap3

### PR DESCRIPTION
**Pull request by EBII**
try to pass travis test to add ldap from pr/#952 the is set red cross due to don't have instal the ldap3 lib

### CODE REVIEW

**Comment by Tntdruid** [comment]
You should make it as a plugin like etc https://github.com/Unrud/RadicaleIMAP

**Comment by pbiering** [comment]
Potentially superseeded by https://github.com/Kozea/Radicale/pull/1218

**Comment by pbiering** [comment]
Sophisticated user authentication should be handover'ed to reverse proxy, as they have a bunch of authentication options already build-in or available via plug-in modules.

**Comment by pbiering** [comment]
superseeded by https://github.com/Kozea/Radicale/pull/1218

**Pull request closed without merging**
