### PR TITLE
Introduced dovecot authN module

### PR DESCRIPTION
**Pull request by galaxy4public**
This work is heavily based on prior art by Giel van Schijndel (#200),
however the code was made Python 3 compatible, error checking
has been improved, and tests were introduced:

```
$ python setup.py test --extras --addopts "-k auth"
[skipped]
Name                        Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------
radicale/auth/dovecot.py       76      2     26      2    96%
[skipped]
=== 34 passed, 16 skipped, 198 deselected in 2.35 seconds ===
```

### CODE REVIEW

**Comment by galaxy4public** [comment]
JFYI, Travis CI fails on other tests not the ones introduced by this PR.

**Comment by Tntdruid** [comment]
I use https://github.com/comzeradd/radicale-imap works great 👍

**Comment by galaxy4public** [comment]
The application is different, this authN module is needed if you want to integrate with Dovecot's authentication backend. I am going to make another PR that uses Dovecot storage API to store calendars and vcards soon, too.

**Comment by galaxy4public** [comment]
Also, passing credentials over a Unix socket is faster and more secure than making an external IMAP call. At least, when Radicale is running on the same instance.

**Comment by Tntdruid** [comment]
The imap plugin was the only way for me, your PR looks like very nice!

**Comment by galaxy4public** [comment]
It's been more than 18 months since this PR was submitted.  Is there anything I could do to expedite its approval and merging into the master branch?

**Review by pbiering — CHANGES_REQUESTED** [review]
please rebase to latest Radicale version 3

**Comment by galaxy4public** [comment]
> please rebase to latest Radicale version 3

Wow! 4 years turn around, this is my first :). Will try to carve out time and see what I can do.

**Comment by pbiering** [comment]
@galaxy4public any update - otherwise I will close for now?!

**Comment by pbiering** [comment]
superseeded

**Pull request closed without merging**
