### PR TITLE
WEB UI: HREF for Upload, Refresh button, and CSS fixes

### PR DESCRIPTION
**Pull request by MatthewHana**
Added WebUI improvements as discussed in discussion #1416 in March 2024.

**New features:**
1. Set the HREF when uploading a collection (limited to 1 upload only)
2. Added a refresh button to refresh the current page (reloads the collections if on the main page and resets any dialog that is open)
3. CSS fixes to further account for different sized screens, texts, and UI
4. Tweaked the loading SVG
 
**Screenshots:**
NewWebUI - Upload HREF
NewWebUI - Refresh button

### CODE REVIEW

**Comment by pbiering** [comment]
@MatthewHana : can you please resolve the conflict?

**Comment by MatthewHana** [comment]
> @MatthewHana : can you please resolve the conflict?

I'm not sure why it's saying there is a conflict. File is conflicting with itself somehow?

**Comment by pbiering** [comment]
have you rebased and/or can you split your single commit into smaller pieces, then I can cherry-pick them and check what leftover causes the problem.

**Comment by MatthewHana** [comment]
I did rebase before I pushed the PR. I rearranged the functions and added documentation in an attempt to resolve the conflict but no avail. This is the "conflict" now:
```
<<<<<<< v3.2-devel
=======

>>>>>>> v3.2-devel
```

**Comment by pbiering** [comment]
> I did rebase before I pushed the PR. I rearranged the functions and added documentation in an attempt to resolve the conflict but no avail. This is the "conflict" now:
> 
> ```
> <<<<<<< v3.2-devel
> =======
> 
> >>>>>>> v3.2-devel
> ```

Looks like one new line got lost, I would assume once you have reapplied it on your side, it should work

upstream:v3.2-devel:/radicale/web/internal_data/fn.js:

```
}


function main() {
```

your:3.2-devel:/radicale/web/internal_data/fn.js:

```
}

function main() {
```

**Comment by MatthewHana** [comment]
> > I did rebase before I pushed the PR. I rearranged the functions and added documentation in an attempt to resolve the conflict but no avail. This is the "conflict" now:
> > ```
> > <<<<<<< v3.2-devel
> > =======
> > 
> > >>>>>>> v3.2-devel
> > ```
> 
> Looks like one new line got lost, I would assume once you have reapplied it on your side, it should work
> 
> upstream:v3.2-devel:/radicale/web/internal_data/fn.js:
> 
> ```
> }
> 
> 
> function main() {
> ```
> 
> your:3.2-devel:/radicale/web/internal_data/fn.js:
> 
> ```
> }
> 
> function main() {
> ```

I restored the empty new line and the conflict is resolved. Hilarious.

**Review by pbiering — APPROVED** [review]
ok

**Pull request merged**
