### PR TITLE
Change distutils to setuptools

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by liZe** [comment]
Is there a reason for that? I'm a bit lost in the distutils/setuptools war, and I don't see the advantages of setuptools for Radicale.

**Comment by jspricke** [comment]
With setuptools you can do `python setup.py develop --user` which only adds links to the git repo, so you can test your development without having to call install every time.

**Comment by untitaker** [comment]
``pip`` depends on ``setuptools``. I think it's safe to argue on that basis that it's now the officially endorsed package to import the ``setup`` function from.

**Comment by liZe** [comment]
I'm convinced!

**Pull request merged**
