### PR TITLE
Fix #715 (Main Component is missing when only recurrence id exists)

### LINKED ISSUE #715: Main Component is missing when only recurrence id exists
I get the exception "Main Component is missing" in 2.1.8. I'm sure in an earlier version maybe 2.1.3 it didn't happen.

The error is here:
https://github.com/Kozea/Radicale/blob/2.1.8/radicale/xmlutils.py#L331

I "fixed" it (not sure if fixed or hacked).
By adding this:

```diff
diff --git a/radicale/xmlutils.py b/radicale/xmlutils.py
index fd9a0d4..b8da5fe 100644
--- a/radicale/xmlutils.py
+++ b/radicale/xmlutils.py
@@ -315,6 +315,7 @@ def _visit_time_ranges(vobject_item, child_name, range_fn, infinity_fn):

     def get_children(components):
         main = None
+        rec_main = None
         recurrences = []
         for comp in components:
             if hasattr(comp, "recurrence_id") and comp.recurrence_id.value:
@@ -322,11 +323,14 @@ def _visit_time_ranges(vobject_item, child_name, range_fn, infinity_fn):
                 if comp.rruleset:
                     # Prevent possible infinite loop
                     raise ValueError("Overwritten recurrence with RRULESET")
+                rec_main = comp
                 yield comp, True, ()
             else:
                 if main is not None:
                     raise ValueError("Multiple main components")
                 main = comp
+        if main is None and len(recurrences) == 1:
+            main = rec_main
         if main is None:
             raise ValueError("Main component missing")
         yield main, False, recurrences
```

### PR DESCRIPTION
**Pull request by trougnouf**
Fix #715 (Main Component is missing when only recurrence id exists) with @balrok 's patch. The file this needs to be applied to changed since he committed in his repo.

The patch hasn't been added after 5 years. It works for me with nextcloud's (originally google's) problematic calendar files, and for others per the bug report.

### CODE REVIEW

**Comment by fcorneli** [comment]
I can confirm that this patch indeed fixes the "Main component missing" error. Please merge this!

**Comment by zi0r** [comment]
Can confirm this resolves the error.  Please merge.

**Comment by janro1** [comment]
works for me too, please merge

**Review by pbiering — APPROVED** [review]
looks ok, also confirmed by other

**Comment by Thorwegian** [comment]
This is not exactly an edge case. All you have to do to reproduce it is to be an Evolution user who also happens to own a tablet (which will be an iPad in most cases). The iOS calendar creates recurring events in a particular way. When you try to edit these in Evolution, they won't save back unless you apply this patch. It was absolutely necessary for me to apply this patch locally for Radicale to be usable for me at all.

**Comment by pbiering** [comment]
Until next release is published, I have now created new builds for Fedora and EPEL containing latest upstream + this patch. Fedora is already in testing repository, EPEL is triggered.

https://koji.fedoraproject.org/koji/packageinfo?packageID=16893
https://src.fedoraproject.org/rpms/radicale

**Comment by fcorneli** [comment]
@pbiering Thanks!

**Comment by jamesob** [comment]
Tested that when this commit is cherry-picked on top of current master, ICS files exported from Google Calendar can be uploaded without encountering the "Main component missing" error.

Please merge this.

**Comment by fcorneli** [comment]
@pbiering Thanks!

**Comment by tobiastom** [comment]
@pbiering Thank you.

**Pull request merged**
