### PR TITLE
Creating addressbooks and calendars in DAVdroid

### PR DESCRIPTION
**Pull request by Unrud**
This fixes some issues that prevent creation of collections in DAVdroid from working smoothly.

The first problem is that the properties **addressbook-home-set** and **calendar-home-set** are returned on _/_ with a value of _/_.
The second problem is that the principal collection doesn't exist for new users.

This is also related to #384.

### CODE REVIEW

**Comment by liZe** [comment]
> The first problem is that the properties addressbook-home-set and calendar-home-set are returned on / with a value of /.

Thanks for fixing this, I broke a lot of things rewriting `xmlutils.py`.

> The second problem is that the principal collection doesn't exist for new users.

That's a big problem. I was really surprised yesterday when I realized that iOS Calendar was able to create the user's collection, and I'm not surprised to see that other clients aren't.

Creating the user's collection in `__call__` is probably the best solution to fix #384. @untitaker what do you think of that?

I'm not sure that I understand your changes in `storage.py`. It looks like a workaround to use `discover` to know if the collection already exists. Maybe we can just always call `create_collection` without calling `discover` (and fix `create_collection` to return the collection as soon as we realize that it already exists)?

**Comment by Unrud** [comment]
> I'm not sure that I understand your changes in ``storage.py``. It looks like a workaround to use ``discover`` to know if the collection already exists.

It didn't correctly detect if a collection is a principal or not. This just fixes that, it has nothing to do with using ``discover`` to check if a collection exists.

The problem is cause by ``attributes`` being ``[""]`` for the path ``/``. This only worked at all because ``path_to_filesystem`` ignores empty path parts.

> Maybe we can just always call ``create_collection`` without calling ``discover``

But then we also always need exclusive access to the storage. Checking if the collections exists can be done with a shared lock.

**Comment by liZe** [comment]
> The problem is cause by attributes being [""] for the path /. This only worked at all because path_to_filesystem ignores empty path parts.

OK, I get it. Can't we just add `[0]` and keep the `return`?

> But then we also always need exclusive access to the storage. Checking if the collections exists can be done with a shared lock.

Yes, needing an exclusive lock for each authenticated request is stupid, you're right.

**Comment by Unrud** [comment]
> Can't we just add ``[0]``

Can you clarify this?

> and keep the ``return``?

What's  the intention behind this check? The ``return`` statement was unreachable before.

The semantic of ``discover`` is not changed by this PR, besides that the value of ``principal`` is correct now.

**Comment by liZe** [comment]
> The semantic of discover is not changed by this PR, besides that the value of principal is correct now.

I understand :)

> The return statement was unreachable before.

Of course, I'm stupid. I thought that discovering was useless when `attributes` was empty, but it's not. Sorry for the noise, and thank you for the tests and the pull request!

**Comment by liZe** [comment]
I've simplified some little things in d322d3f, feel free to review!

**Pull request merged**
