### PR TITLE
Extra information about git hook

### LINKED ISSUE #876: Default git hook does not work out of the box
Hi,

Enabling
```
hook = ([ -d .git ] || git init) && git add -A && (git diff --cached --quiet || git commit -m "Changes by "%(user)s)
```
leads to:
```
[7fa9f2c42ae8] DEBUG: Running hook
[7fa9f2c42ae8] DEBUG: Captured stderr hook:

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'radicale@9009506c3d73.(none)')

[7fa9f2c42ae8] ERROR: An exception occurred during MKCOL request on '/myuser/0527aa01-08d0-01d4-4793-692bece1feeb/': Command '([ -d .git ] || git init) && git add -A && (git diff --cached --quiet || git commit -m "Changes by "myuser)' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/radicale/__init__.py", line 332, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/lib/python3.6/site-packages/radicale/__init__.py", line 505, in _handle_request
    environ, base_prefix, path, user)
  File "/usr/lib/python3.6/site-packages/radicale/__init__.py", line 721, in do_MKCOL
    return client.CREATED, {}, None
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/lib/python3.6/site-packages/radicale/storage.py", line 1587, in acquire_lock
    raise subprocess.CalledProcessError(p.returncode, p.args)
subprocess.CalledProcessError: Command '([ -d .git ] || git init) && git add -A && (git diff --cached --quiet || git commit -m "Changes by "myuser)' returned non-zero exit status 128.
```

Workaround is to run
```
git config user.email "you@example.com"
```
in the collections folder.

Would be great if you could fix that!

### PR DESCRIPTION
**Pull request by mpasternak**
Fixes #876

### CODE REVIEW

**Comment by mpasternak** [comment]
Please also see pull request #913

**Review by pbiering — APPROVED** [review]
looks good

**Comment by pbiering** [comment]
@mpasternak : this PR has conflicts, please rebase, thank you!

**Comment by mpasternak** [comment]
Would love to, but I have hardly any time to commit. Anyone willing to work on this patch? Obviously it is needed….

**Review by pbiering — CHANGES_REQUESTED** [review]
Please request PR for `DOCUMENTATION.md`

**Comment by pbiering** [comment]
will be covered by https://github.com/Kozea/Radicale/pull/1631

**Pull request closed without merging**
